name: Docker CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: DockerHub Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Create production env file
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIRECT_URI_GOOGLE: ${{ secrets.REDIRECT_URI_GOOGLE }}
          REFRESH_TOKEN_GOOGLE: ${{ secrets.REFRESH_TOKEN_GOOGLE }}
          CLIENT_ID_GOOGLE: ${{ secrets.CLIENT_ID_GOOGLE }}
          CLIENT_SECRET_GOOGLE: ${{ secrets.CLIENT_SECRET_GOOGLE }}
        run: |
          touch .env.production
          echo CORS_ORIGIN=https://codeisscience.com >> .env.production
          echo SESSION_SECRET=$SESSION_SECRET >> .env.production
          echo DATABASE_URL=$DATABASE_URL >> .env.production
          echo REDIS_URL=$REDIS_URL >> .env.production
          echo REDIRECT_URI_GOOGLE=$REDIRECT_URI_GOOGLE >> .env.production
          echo REFRESH_TOKEN_GOOGLE=$REFRESH_TOKEN_GOOGLE >> .env.production
          echo CLIENT_ID_GOOGLE=$CLIENT_ID_GOOGLE >> .env.production
          echo CLIENT_SECRET_GOOGLE=$CLIENT_SECRET_GOOGLE >> .env.production

      - name: Build the Docker Image
        run: docker build -t codeisscience/journal-policy-tracker-backend:$(echo "$(date "+%Y%m%d%H%M") - ($(date +%M)%5)" | bc) .

      - name: Push the Docker Image to DockerHub
        run: docker push codeisscience/journal-policy-tracker-backend:$(echo "$(date "+%Y%m%d%H%M") - ($(date +%M)%5)" | bc)
